### ISSUE TITLE
CTA: contact us!

### ISSUE THREAD

**Issue by kamilsi** [ttscience/ttscience_blog#9]
Chcielibyśmy, żeby każdy artykuł kończył się call to action - skontaktuj się z nami. Może stopkę zmodyfikować? Może ten pasek do share-owania artykułów?

Jeśli to trudne - chcemy każdy post taki CTA kończyć

**Comment by kamilpytlak** [comment]
Done: https://github.com/ttscience/ttscience_blog/pull/6/commits/9ea11626b3abaa9bc2f778adec70b402592fc60f
